name: Design System CI

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Code Style Check
        run: ./gradlew lintDevDebug

      - name: Run Local Unit Tests
        run: ./gradlew testDevDebugUnitTest

      - name: Build Debug APK
        run: ./gradlew assembleDevDebug