name: Design System CD

on:
  push:
    branches: [ "main" ]

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./android

      - name: Build Debug APK
        run: ./gradlew assembleDevDebug
        working-directory: ./android

      - name: Upload to Firebase App Distribution
        uses: w9jds/firebase-action@v11.16.0
        with:
          args: appdistribution:distribute android/app/build/outputs/apk/dev/debug/app-dev-debug.apk --app ${{ secrets.FIREBASE_APP_ID }}
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
